// Project coordinates verified from the Google Maps links supplied for these sites.
export const PROJECT_LOCATIONS = [
  {
    id: "tvs",
    name: "TVS Lanka",
    location: "Poruwadanda",
    description: "Vehicle assembly complex",
    latitude: 6.7434949,
    longitude: 80.1101455,
    logo: "/clients/tvs-lanka.jpg",
    mapsUrl: "https://maps.app.goo.gl/tcPVxA1YUZJZGBw3A?g_st=ac",
    galleryId: "tvs",
  },
  {
    id: "rocell",
    name: "Rocell",
    location: "Poruwadanda",
    description: "Project location",
    latitude: 6.7423833,
    longitude: 80.1108181,
    logo: "/clients/rocell.jpg",
    mapsUrl: "https://maps.app.goo.gl/wYaeZfbEf49QJP3d7?g_st=ac",
    galleryId: "rocell",
  },
  {
    id: "kap",
    name: "KAP",
    location: "Poruwadanda",
    description: "Project location",
    latitude: 6.7383428,
    longitude: 80.1101522,
    logo: "/clients/kap-logo.png",
    mapsUrl: "https://maps.app.goo.gl/enhBzKLTuh5M54f19?g_st=ac",
    galleryId: "kap",
  },
  {
    id: "spa-ceylon",
    name: "Spa Ceylon",
    location: "Wadduwa",
    description: "Project location",
    latitude: 6.667918,
    longitude: 79.945961,
    logo: "/clients/spa-ceylon-optimized.webp",
    mapsUrl: "https://goo.gl/maps/M6BC9FMQvcETJTrLA?g_st=ac",
    galleryId: "spaCeylon",
  },
  {
    id: "space-logistics",
    name: "Space Logistics",
    location: "Wadduwa",
    description: "Warehouse complex",
    latitude: 6.6669791,
    longitude: 79.9461546,
    logo: "/clients/space-logistics-navy.webp",
    mapsUrl: "https://maps.app.goo.gl/J3uqrfJk9CF86qRF8?g_st=ac",
    galleryId: "spaceLogistics",
  },
];
